name: Alur Kerja Review Kode

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositori
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependensi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Jalankan Pylint dan buat GitHub issue
        run: |
          python src/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
